=== yayEvy/vscreate/run-data/config/valkyrienskies/schemas/vs_core_server.schema.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "type" : "object",
  "properties" : {
    "enableUdp" : {
      "type" : "boolean",
      "description" : "Is udp enabled? If not, the server will only use TCP"
    },
    "physics" : {
      "type" : "object",
      "properties" : {
        "lodDetail" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The detail of the collision LOD of ships, higher values are more detailed but heavier to compute. Setting this to 0 disables Lod, but may cause instability!"
        },
        "maxDePenetrationSpeed" : {
          "type" : "number",
          "format" : "double",
          "description" : "Limit the max collision de-penetration speed so that rigid bodies don't go flying apart when they overlap"
        },
        "physicsSpeed" : {
          "type" : "number",
          "format" : "double",
          "description" : "How fast the physics is running. 1.0 is full speed, 0.5 is 50% speed, etc."
        },
        "physicsSubSteps" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Sets number of sub-steps used by Krunch"
        },
        "positionIterations" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The maximum number of iterations used by the physics engine to resolve positions. Higher values are more accurate but heavier to compute",
          "default" : "8",
          "minimum" : 1,
          "maximum" : 3E+1
        },
        "velocityIterations" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "The maximum number of iterations used by the physics engine to resolve velocity. Higher values are more accurate but heavier to compute",
          "default" : "2",
          "minimum" : 1,
          "maximum" : 3E+1
        }
      },
      "additionalProperties" : false,
      "description" : "All related settings to the physics engine"
    },
    "pt" : {
      "type" : "object",
      "properties" : {
        "physicsTicksPerGameTick" : {
          "type" : "integer",
          "format" : "int32"
        },
        "synchronizePhysics" : {
          "type" : "boolean",
          "description" : "Synchronize the physics thread and the game thread"
        },
        "terrainBakingThreadPriority" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Thread priority of terrain baking threads. 5 is default priority, higher is higher priority, lower is lower priority."
        },
        "terrainBakingThreads" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Number of terrain baking threads, more is good for preventing stutters when flying fast ships. However, too many will overload the cpu which will lag the game."
        },
        "terrainDeletionThreadPriority" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Thread priority of terrain deletion threads. These are used to clean up memory, so they can be lower priority than."
        },
        "terrainDeletionThreads" : {
          "type" : "integer",
          "format" : "int32",
          "description" : "Number of terrain deletion threads. Typically just 1 is fine."
        }
      },
      "additionalProperties" : false,
      "title" : "Physics Thread Settings"
    },
    "shipLoadDistance" : {
      "type" : "number",
      "format" : "double",
      "description" : "Ship load distance in blocks"
    },
    "shipUnloadDistance" : {
      "type" : "number",
      "format" : "double",
      "description" : "Ship unload distance in blocks"
    },
    "sp" : {
      "type" : "object",
      "properties" : {
        "enableBlockCornerConnectivity" : {
          "type" : "boolean",
          "description" : "Enable/Disable Block Corner Connectivity (WARNING! May significantly increase memory usage)"
        },
        "enableBlockEdgeConnectivity" : {
          "type" : "boolean",
          "description" : "Enable/Disable Block Edge Connectivity (WARNING! May significantly increase memory usage)"
        },
        "enableConnectivity" : {
          "type" : "boolean",
          "description" : "Enable/Disable Connectivity (May reduce memory usage. Use [enableSplitting] instead if you just want to disable ship splitting.)"
        },
        "enableSplitting" : {
          "type" : "boolean",
          "description" : "Enable/Disable Splitting (Disabling this setting will not prevent the use of Air Pockets.)"
        },
        "enableWorldConnectivity" : {
          "type" : "boolean",
          "description" : "Enable/Disable World Connectivity (Experimental!)"
        },
        "verboseConnectivityLogging" : {
          "type" : "boolean",
          "description" : "Enable verbose logging of connectivity (May result in very large log files)"
        }
      },
      "additionalProperties" : false,
      "title" : "Connectivity Settings (Experimental)"
    },
    "udpPort" : {
      "type" : "integer",
      "format" : "int32",
      "description" : "Port to attempt to establish UDP connections on"
    },
    "$schema" : {
      "type" : "string"
    }
  },
  "additionalProperties" : false
}

=== yayEvy/vscreate/run-data/config/valkyrienskies/vs_core_server.json
{
  "pt" : {
    "synchronizePhysics" : false,
    "physicsTicksPerGameTick" : 3,
    "terrainBakingThreads" : 12,
    "terrainBakingThreadPriority" : 5,
    "terrainDeletionThreads" : 1,
    "terrainDeletionThreadPriority" : 4
  },
  "sp" : {
    "enableConnectivity" : true,
    "enableWorldConnectivity" : false,
    "enableBlockEdgeConnectivity" : true,
    "enableBlockCornerConnectivity" : false,
    "enableSplitting" : false,
    "verboseConnectivityLogging" : false
  },
  "udpPort" : 25565,
  "enableUdp" : false,
  "shipLoadDistance" : 128.0,
  "shipUnloadDistance" : 196.0,
  "physics" : {
    "lodDetail" : 512,
    "physicsSubSteps" : 1,
    "positionIterations" : 8,
    "velocityIterations" : 2,
    "maxDePenetrationSpeed" : 10.0,
    "physicsSpeed" : 1.0
  },
  "$schema" : "schemas/vs_core_server.schema.json"
}
